kind: pipeline
name: part1

steps:
- name: package maven
  image: maven
  commands:
  - cd maven-simplest
  - mvn package

---

kind: pipeline
name: part2

steps:
- name: package gradle
  image: 8-jdk	
  commands:
  - cd gradle-simplest
  - ./gradlew shadowJar
